# DataSource Config
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: kobe
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672